server:
    port: 8066
    tomcat:
        uri-encoding: UTF-8

spring:
    datasource:                                     # 数据源配置
        type: com.zaxxer.hikari.HikariDataSource    # 数据源类型:  hikariCP
        driver-class-name: com.mysql.jdbc.Driver    # mysql驱动
        url: jdbc:mysql://139.196.124.187:3306/mall-shop-prod?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: yunfeng
    redis:
        database: 1
        host: 139.196.124.187
        port: 6379
        password: yunfeng

mybatis:
    type-aliases-package: com.yunfeng.pojo      # 所有pojo类所在包路径
    mapper-locations: classpath:mapper/*.xml    # mapper映射文件
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
    mappers: com.yunfeng.my.mapper.MyMapper
    not-empty: false # 在进行数据库操作的时候，判断表达式username != null，是否追加 username != ''
    identity: MYSQL
# 分页插件配置
pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true

# fdfs


fdfs:
    connect-timeout: 30000 # 连接超时时间
    so-timeout: 30000      # 读取超时时间
    tracker-list: 139.196.124.187:22122      # tracker所在的ip地址和端口号
