server:
    port: 8088

spring:
    datasource:                                     # 数据源配置
        type: com.zaxxer.hikari.HikariDataSource    # 数据源类型:  hikariCP
        driver-class-name: com.mysql.jdbc.Driver    # mysql驱动
        url: jdbc:mysql://localhost:3306/mall-shop-prod?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: yunfeng
    redis:
        database: 1
        host: 139.196.124.187
        port: 6379
        password: yunfeng
