#############################################
#
# web访问端口号 约定8088
#
#############################################
server:
    tomcat:
        uri-encoding: UTF-8
    max-http-header-size: 8KB

#############################################
#
# 配置数据源信息
#
#############################################
spring:
    profiles:
        active: prod
        hikari:
            connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发送SQLException,默认30s
            minimum-idle: 5                 # 最小连接数
            maximum-pool-size: 20           # 最大连接数
            auto-commit: true               # 自动提交
            idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认10分钟
            pool-name: DateSOurceHikariCP   # 连接池名字
            max-lifetime: 1800000           # 连接的生命时长（毫秒），超时则被释放（retired）默认30分钟：1800000毫秒
            connection-test-query: SELECT 1
    servlet:
        multipart:
            max-file-size: 512000  # 文件上传大小限制为500kb
            max-request-size: 512000 # 文件上传最大请求为500kb

#############################################
#
# mybatis配置
#
#############################################
mybatis:
    type-aliases-package: com.yunfeng.pojo      # 所有pojo类所在包路径
    mapper-locations: classpath:mapper/*.xml    # mapper映射文件

#############################################
#
# mybatis mapper配置
#
#############################################
mapper:
    mappers: com.yunfeng.my.mapper.MyMapper
    not-empty: false # 在进行数据库操作的时候，判断表达式username != null，是否追加 username != ''
    identity: MYSQL
# 分页插件配置
pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
